name: my first workflow
on: 
- push

jobs: 
    my_first_pipeline:
        runs-on: ubuntu-latest

        steps:
        - name: cowsay something
          uses: mscoutermarsh/cowsays-action@master
          with: 
            text: ${{ github.event.head_commit.message }}
            color: 'blue'

        - name: checkout the repo
          uses: actions/checkout@v3

        - name: list the files in our repository
          run: ls -l