name: my first workflow
on: 
- push

jobs: 
    my_first_pipeline:
        runs-on: ubuntu-latest

        steps:
        - name: greetings
          run: echo "hello world"

        - name: what is the time on the runner
          run: date

        - name: list filesystem 
          run: ls -l /

        - name: cowsay something
          uses: mscoutermarsh/cowsays-action@master
          with: 
            text: ${{ github.event.head_commit.message }}
            color: 'blue'